version: "3.1"
services:
  db:
    image: mariadb:10.4
    ports: 
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_DATABASE: mariadb
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: mariadb
    volumes:
      - ../dump:/docker-entrypoint-initdb.d
      - ../conf:/etc/mysql/conf.d
      - mariadb-data:/var/lib/mysql
    networks:
      - default

  www:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "80:80"
    volumes:
      - ../www:/var/www/html
    links:
      - db
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links: 
      - db:db
    ports:
      - 8000:80
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_DATABASE: mariadb
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: mariadb

volumes:
  mariadb-data:
